use std::collections::HashSet;
use std::env;
use std::fs;
use std::path::Path;

use serde::Deserialize;

#[derive(Debug)]
struct CountryRow {
    country_code: String,
    country_name: String,
    country_aliases: Vec<String>,
    lat: f64,
    lon: f64,
    currency_code: String,
    currency_name: String,
    currency_aliases: Vec<String>,
    currency_focal_country_code: String,
}

#[derive(Debug, Deserialize)]
struct RepresentativeCityRow {
    country_code: String,
    city_code: String,
    city_name: String,
    country_name: String,
    timezone: String,
    currency_code: String,
}

fn main() {
    println!("cargo:rerun-if-changed=data/countries.csv");
    println!("cargo:rerun-if-changed=data/representative_cities.json");

    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("manifest dir should exist");
    let countries_path = Path::new(&manifest_dir).join("data/countries.csv");
    let representative_cities_path =
        Path::new(&manifest_dir).join("data/representative_cities.json");

    let countries = parse_countries_csv(&countries_path);
    let representative_cities = parse_representative_cities_json(&representative_cities_path);
    validate_representative_cities(&countries, &representative_cities);

    let generated = render_reference_data(&countries, &representative_cities);
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR should exist");
    let output_path = Path::new(&out_dir).join("reference_data.rs");
    fs::write(output_path, generated).expect("generated reference data should be written");
}

fn parse_countries_csv(path: &Path) -> Vec<CountryRow> {
    let contents = fs::read_to_string(path).expect("countries.csv should be readable");
    let mut rows = Vec::new();

    for (line_number, line) in contents.lines().enumerate() {
        if line_number == 0 || line.trim().is_empty() {
            continue;
        }

        let columns: Vec<&str> = line.split(',').collect();
        assert!(
            columns.len() == 9,
            "countries.csv line {} should have 9 columns, got {}",
            line_number + 1,
            columns.len()
        );

        rows.push(CountryRow {
            country_code: columns[0].trim().to_string(),
            country_name: columns[1].trim().to_string(),
            country_aliases: split_aliases(columns[2]),
            lat: columns[3]
                .trim()
                .parse()
                .expect("country latitude should parse"),
            lon: columns[4]
                .trim()
                .parse()
                .expect("country longitude should parse"),
            currency_code: columns[5].trim().to_string(),
            currency_name: columns[6].trim().to_string(),
            currency_aliases: split_aliases(columns[7]),
            currency_focal_country_code: columns[8].trim().to_string(),
        });
    }

    rows
}

fn parse_representative_cities_json(path: &Path) -> Vec<RepresentativeCityRow> {
    let contents = fs::read_to_string(path).expect("representative_cities.json should be readable");
    serde_json::from_str(&contents).expect("representative_cities.json should parse")
}

fn validate_representative_cities(
    countries: &[CountryRow],
    representative_cities: &[RepresentativeCityRow],
) {
    let country_codes: HashSet<&str> = countries
        .iter()
        .map(|row| row.country_code.as_str())
        .collect();
    let currency_codes: HashSet<&str> = countries
        .iter()
        .map(|row| row.currency_code.as_str())
        .collect();

    for city in representative_cities {
        assert!(
            country_codes.contains(city.country_code.as_str()),
            "representative city references unknown country code {}",
            city.country_code
        );
        assert!(
            currency_codes.contains(city.currency_code.as_str()),
            "representative city references unknown currency code {}",
            city.currency_code
        );
    }
}

fn render_reference_data(
    countries: &[CountryRow],
    representative_cities: &[RepresentativeCityRow],
) -> String {
    let mut output = String::new();
    output.push_str("// generated by build.rs\n");

    output.push_str("pub const COUNTRY_REFERENCES: &[CountryReference] = &[\n");
    for row in countries {
        output.push_str("    CountryReference {\n");
        output.push_str(&format!("        code: {:?},\n", row.country_code));
        output.push_str(&format!("        name: {:?},\n", row.country_name));
        output.push_str(&format!(
            "        aliases: &{},\n",
            render_string_slice(&row.country_aliases)
        ));
        output.push_str(&format!("        lat: {:?},\n", row.lat));
        output.push_str(&format!("        lon: {:?},\n", row.lon));
        output.push_str("    },\n");
    }
    output.push_str("];\n\n");

    output.push_str("pub const CURRENCY_REFERENCES: &[CurrencyReference] = &[\n");
    let mut seen_currencies = HashSet::new();
    for row in countries {
        if !seen_currencies.insert(row.currency_code.clone()) {
            continue;
        }

        output.push_str("    CurrencyReference {\n");
        output.push_str(&format!("        code: {:?},\n", row.currency_code));
        output.push_str(&format!("        name: {:?},\n", row.currency_name));
        output.push_str(&format!(
            "        aliases: &{},\n",
            render_string_slice(&row.currency_aliases)
        ));
        output.push_str(&format!(
            "        focal_country_code: {:?},\n",
            row.currency_focal_country_code
        ));
        output.push_str("    },\n");
    }
    output.push_str("];\n\n");

    output.push_str(
        "pub const REPRESENTATIVE_CITY_REFERENCES: &[RepresentativeCityReference] = &[\n",
    );
    for row in representative_cities {
        output.push_str("    RepresentativeCityReference {\n");
        output.push_str(&format!("        country_code: {:?},\n", row.country_code));
        output.push_str(&format!("        city_code: {:?},\n", row.city_code));
        output.push_str(&format!("        city_name: {:?},\n", row.city_name));
        output.push_str(&format!("        country_name: {:?},\n", row.country_name));
        output.push_str(&format!("        timezone: {:?},\n", row.timezone));
        output.push_str(&format!(
            "        currency_code: {:?},\n",
            row.currency_code
        ));
        output.push_str("    },\n");
    }
    output.push_str("];\n");

    output
}

fn split_aliases(value: &str) -> Vec<String> {
    value
        .split('|')
        .map(str::trim)
        .filter(|alias| !alias.is_empty())
        .map(ToString::to_string)
        .collect()
}

fn render_string_slice(values: &[String]) -> String {
    let rendered = values
        .iter()
        .map(|value| format!("{:?}", value))
        .collect::<Vec<_>>()
        .join(", ");
    format!("[{}]", rendered)
}
